name: GA0 step

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: 23f1002246@ds.study.iitm.ac.in
        run: echo "Hello from GA0!"
